/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.training.fooddelivery;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {

    }
}
